### ISSUE TITLE
class ReceiverManager error!

### ISSUE THREAD

**Issue by bewuluck0912** [kotvertolet/youtube-audio-player#3]
When I turn off the app and turn it on again, sometimes I get an error like this.

Logcat Message:  

    Process: com.github.kotvertolet.youtubeaudioplayer, PID: 2653
    java.lang.RuntimeException: Unable to create service com.github.kotvertolet.youtubeaudioplayer.services.ExoPlayerService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Context.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3817)
        at android.app.ActivityThread.access$2100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Context.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference
        at com.github.kotvertolet.youtubeaudioplayer.utilities.ReceiverManager.registerGlobalReceiver(ReceiverManager.java:43)
        at com.github.kotvertolet.youtubeaudioplayer.services.ExoPlayerService.registerReceivers(ExoPlayerService.java:286)
        at com.github.kotvertolet.youtubeaudioplayer.services.ExoPlayerService.onCreate(ExoPlayerService.java:85)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3807)
        at android.app.ActivityThread.access$2100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by antonyhaman** [comment]
I've made a new release where I fixed some issues, check it
