### ISSUE TITLE
Error trying to play any video

### ISSUE THREAD

**Issue by Jeffersonceo** [kotvertolet/youtube-audio-player#6]
I'm facing problems, errors when playing the songs
the app closes!

`01-30 12:44:13.778 32662-493/com.github.kotvertolet.youtubeaudioplayer E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.github.kotvertolet.youtubeaudioplayer, PID: 32662
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.b(SourceFile:12)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(SourceFile:1)
        at com.github.kotvertolet.youtubeaudioplayer.utilities.AudioStreamsUtils.extractYoutubeVideoData(AudioStreamsUtils.java:30)
        at com.github.kotvertolet.youtubeaudioplayer.tasks.AudioStreamExtractionAsyncTask.doInBackground(AudioStreamExtractionAsyncTask.java:41)
        at com.github.kotvertolet.youtubeaudioplayer.tasks.AudioStreamExtractionAsyncTask.doInBackground(AudioStreamExtractionAsyncTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)`

**Comment by antonyhaman** [comment]
This is a bug in youtubejextractor library, I'm working on it

**Comment by antonyhaman** [comment]
Fixed
